New-PSUScript -Name "RegisterKeyVault.ps1" -Description "RegisterKeyVault.ps1" -Path "RegisterKeyVault.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "NewUser.ps1" -Description "NewUser.ps1" -Path "NewUser.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "CreateServiceCatalogTables.ps1" -Description "CreateServiceCatalogTables.ps1" -Path "CreateServiceCatalogTables.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "NewServiceRequest.ps1" -Description "NewServiceRequest.ps1" -Path "NewServiceRequest.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "GetServiceRequest.ps1" -Description "GetServiceRequest.ps1" -Path "GetServiceRequest.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "UpdateServiceRequest.ps1" -Description "UpdateServiceRequest.ps1 [-Id] <int> [-Status] <int> [-Description] <string> [<CommonParameters>]" -Path "UpdateServiceRequest.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "SendTeamsMessage.ps1" -Description "SendTeamsMessage.ps1" -Path "SendTeamsMessage.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "SendEmail.ps1" -Description "SendEmail.ps1" -Path "SendEmail.ps1" -InformationAction "SilentlyContinue" 
New-PSUScript -Name "ProvisionMachines.ps1" -Description "ProvisionMachines.ps1" -Path "ProvisionMachines.ps1" -InformationAction "SilentlyContinue"